### ISSUE TITLE
New wp.org banners and icons

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/invoicing-quotes#64]

**Comment by basantaux** [comment]
![icon-128](https://user-images.githubusercontent.com/52257358/104926483-3acf6880-59c6-11eb-9a8a-0aae518d26e7.png)
![icon-256](https://user-images.githubusercontent.com/52257358/104926488-3c009580-59c6-11eb-8f33-d01474eb40b8.png)
![wp-banner-772x250](https://user-images.githubusercontent.com/52257358/104926492-3d31c280-59c6-11eb-9ec4-2ae0e00aa3e5.png)
![wp-banner-1544x500png](https://user-images.githubusercontent.com/52257358/104926493-3dca5900-59c6-11eb-9808-3117cbb96105.png)
