### ISSUE TITLE
Fatal error when viewing the Invoices from buddypress.

### ISSUE THREAD

**Issue by laranz** [AyeCode/invoicing-quotes#68]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/208945/107230986-bd879880-6a45-11eb-8621-f8cd0ac7e827.png">

 Fatal error: Uncaught ArgumentCountError: Too few arguments to function Wpinv_Quotes::filter_user_invoice_actions(), 2 passed in /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php on line 287 and exactly 3 expected in /Users/laranz/Sites/geo/wp-content/plugins/invoicing-quotes/includes/class-wpinv-quotes.php:541 Stack trace: #0 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(287): Wpinv_Quotes->filter_user_invoice_actions(Array, Object(WPInv_Invoice)) #1 /Users/laranz/Sites/geo/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array) #2 /Users/laranz/Sites/geo/wp-content/plugins/invoicing/includes/class-wpinv-bp-core.php(144): apply_filters('wpinv_user_invo...', Array, Object(WPInv_Invoice)) #3 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(287): WPInv_BP_Component->invoices_content('') #4 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #5 /Users/laranz/Sites/geo/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #6 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-templates/bp-nouveau/includes/template-tags.php(36): do_action('bp_template_con...') #7 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-templates/bp-nouveau/includes/template-tags.php(55): bp_nouveau_hook(Array) #8 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-templates/bp-nouveau/buddypress/members/single/plugins.php(35): bp_nouveau_plugin_hook('content') #9 /Users/laranz/Sites/geo/wp-includes/template.php(730): require_once('/Users/laranz/S...') #10 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-templates/bp-nouveau/includes/members/functions.php(333): load_template('/Users/laranz/S...', true) #11 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-templates/bp-nouveau/includes/members/template-tags.php(667): bp_nouveau_member_get_template_part('plugins') #12 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-templates/bp-nouveau/buddypress/members/single/home.php(27): bp_nouveau_member_template_part() #13 /Users/laranz/Sites/geo/wp-includes/template.php(732): require('/Users/laranz/S...') #14 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-core/bp-core-template-loader.php(165): load_template('/Users/laranz/S...', false, Array) #15 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-core/bp-core-template-loader.php(67): bp_locate_template(Array, true, false, Array) #16 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-core/bp-core-template-loader.php(350): bp_get_template_part('members/single/...', NULL, Array) #17 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-members/classes/class-bp-members-theme-compat.php(212): bp_buffer_template_part('members/single/...', NULL, false) #18 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(287): BP_Members_Theme_Compat->single_dummy_content('') #19 /Users/laranz/Sites/geo/wp-includes/plugin.php(212): WP_Hook->apply_filters('', Array) #20 /Users/laranz/Sites/geo/wp-content/plugins/buddypress/bp-core/bp-core-theme-compatibility.php(761): apply_filters('bp_replace_the_...', '') #21 /Users/laranz/Sites/geo/wp-includes/class-wp-hook.php(287): bp_replace_the_content('') #22 /Users/laranz/Sites/geo/wp-includes/plugin.php(212): WP_Hook->apply_filters('', Array) #23 /Users/laranz/Sites/geo/wp-includes/post-template.php(253): apply_filters('the_content', '') #24 /Users/laranz/Sites/geo/wp-content/themes/primer/templates/parts/loop/page-content.php(24): the_content() #25 /Users/laranz/Sites/geo/wp-includes/template.php(732): require('/Users/laranz/S...') #26 /Users/laranz/Sites/geo/wp-includes/template.php(676): load_template('/Users/laranz/S...', false, Array) #27 /Users/laranz/Sites/geo/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #28 /Users/laranz/Sites/geo/wp-content/themes/primer/content-page.php(21): get_template_part('templates/parts...', 'content') #29 /Users/laranz/Sites/geo/wp-includes/template.php(732): require('/Users/laranz/S...') #30 /Users/laranz/Sites/geo/wp-includes/template.php(676): load_template('/Users/laranz/S...', false, Array) #31 /Users/laranz/Sites/geo/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #32 /Users/laranz/Sites/geo/wp-content/themes/primer/page.php(28): get_template_part('content', 'page') #33 /Users/laranz/Sites/geo/wp-includes/template-loader.php(106): include('/Users/laranz/S...') #34 /Users/laranz/Sites/geo/wp-blog-header.php(19): require_once('/Users/laranz/S...') #35 /Users/laranz/Sites/geo/index.php(17): require('/Users/laranz/S...') #36 /Users/laranz/.composer/vendor/laravel/valet/server.php(219): require('/Users/laranz/S...') #37 {main} thrown in /Users/laranz/Sites/geo/wp-content/plugins/invoicing-quotes/includes/class-wpinv-quotes.php on line 541

**Comment by picocodes** [comment]
Fixed
